[package]
name = "zzclawterm-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
gpui_platform.workspace = true
zzclawterm-core.workspace = true
zzclawterm-desktop.workspace = true
zzclawterm-ui.workspace = true
rust-embed.workspace = true

tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
usvg.workspace = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[lib]
name = "zzclawterm_app"
path = "src/lib.rs"

[[bin]]
name = "zzclawterm"
path = "src/main.rs"


[features]
default = ["font-kit"]
font-kit = ["gpui_platform/font-kit"]
